#+title: ISSR
This is the core functionality that is needed for an ISSR back-end to be implemented. Make sure to see the [[https://github.com/interactive-ssr/client/blob/master/main.org][main readme]] for the ISSR project and [[https://github.com/interactive-ssr/client/blob/master/getting-started.org][setup issr.js]]. ISSR allows you to make interactive web pages without writing client scripting. Hunchenissr is the reference implementation, so if there are any discrepancies between back-ends Hunchenissr is always correct (unless is an error).

* Building 
For now it only works in Common Lisp, I am working on porting to JVM (via ABCL) and everything else (via ECL). If you want to help with either of those please make a pull request in a non-master branch since the master branch is for Common Lisp only.

1. clone repository to =quicklisp/local-projects=
2. ~(ql:quickload 'issr-core)~

Look in the source file for documentation on the symbols

* Issues
If you find any bugs of have any issues (installing, using, questions) use the Github issue tracker.

* Contact
If you want to contact me about collaboration, licensing, implementing a new back-end, etc. You can use the email in issr-core.asd.
